### ISSUE TITLE
/model/predict returns unexpected result

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Toxic-Comment-Classifier#7]
No big deal, but 

```
{
 "text": [""]
}
```

it's odd that nothing can be interpreted as something

```
     {
        "toxic": 0.0015665121609345078,
        "severe_toxic": 0.00011611604713834822,
        "obscene": 0.0004790136299561709,
        "threat": 0.00007217624806798995,
        "insult": 0.0003883792378474027,
        "identity_hate": 0.0003294776252005249
      }
```

and similarly a meaningless combination of characters

```
{
 "text": ["khdcuc4wcc5jlcnw"]
}
```

and numbers
```
{
 "text": ["123"]
}
```

Note sure if there's something that can be done to eliminate noise that's a result of garbage input.

**Comment by MLnick** [comment]
For the first case, I think we can catch an empty string input and return either all zeros or an empty dict? Would probably need to be an empty dict since the empty string could be in position other than 0 in the list.

For the others there is not much to be done, but I am somewhat surprised it returns any prediction since those words won't be in the vocab (and I don't think this BERT model has char-level embeddings cc @splovyt?). I would expect it to return zeros for out of vocab words.

**Comment by splovyt** [comment]
Interesting observation!

I was able to print out the generated tokens (used for classification) and this is what I can derive.

- For the empty string:
```
tokens: [CLS] [SEP]
```

- For `khdcuc4wcc5jlcnw`:
```
tokens: [CLS] k ##hd ##cu ##c ##4 ##wc ##c ##5 ##j ##lc ##n ##w [SEP]
```

- For `123`:
```
tokens: [CLS] 123 [SEP]
```

The [CLS] token is the sentence-level token that will be used for the actual prediction. I think it generally carries some weight, even when no sentence is present.. I definitely don't know for sure though.. Regarding the other meaningless combination of characters, it gets split up in word groups who might carry some level of meaning. The example often used to showcase the split is this one: `puppeteer` to `puppet ##eer`. I think this gives some insight, but I cannot draw a definite conclusion. 

Regarding filtering garbage input, this will 'cost' a couple of rule-based lines of code. I probably won't be able to cover all of the adverse results with it, but I can give it a try. Do you want me to try and cover this? @ptitzler @MLnick
